package bookshop;
// Generated Oct 29, 2016 7:28:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Authors generated by hbm2java
 */
public class Authors  implements java.io.Serializable {


     private String authorId;
     private String name;
     private Set<Booksauthors> booksauthorses = new HashSet<Booksauthors>(0);

    public Authors() {
    }

	
    public Authors(String authorId) {
        this.authorId = authorId;
    }
    public Authors(String authorId, String name, Set<Booksauthors> booksauthorses) {
       this.authorId = authorId;
       this.name = name;
       this.booksauthorses = booksauthorses;
    }
   
    public String getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Booksauthors> getBooksauthorses() {
        return this.booksauthorses;
    }
    
    public void setBooksauthorses(Set<Booksauthors> booksauthorses) {
        this.booksauthorses = booksauthorses;
    }




}


