package bookshop;
// Generated Oct 29, 2016 7:28:58 PM by Hibernate Tools 4.3.1



/**
 * Booksauthors generated by hbm2java
 */
public class Booksauthors  implements java.io.Serializable {


     private BooksauthorsId id;
     private Authors authors;
     private Books books;
     private Integer seqNo;

    public Booksauthors() {
    }

	
    public Booksauthors(BooksauthorsId id, Authors authors, Books books) {
        this.id = id;
        this.authors = authors;
        this.books = books;
    }
    public Booksauthors(BooksauthorsId id, Authors authors, Books books, Integer seqNo) {
       this.id = id;
       this.authors = authors;
       this.books = books;
       this.seqNo = seqNo;
    }
   
    public BooksauthorsId getId() {
        return this.id;
    }
    
    public void setId(BooksauthorsId id) {
        this.id = id;
    }
    public Authors getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Authors authors) {
        this.authors = authors;
    }
    public Books getBooks() {
        return this.books;
    }
    
    public void setBooks(Books books) {
        this.books = books;
    }
    public Integer getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }




}


