package bookshop;
// Generated Oct 29, 2016 7:28:58 PM by Hibernate Tools 4.3.1



/**
 * BooksauthorsId generated by hbm2java
 */
public class BooksauthorsId  implements java.io.Serializable {


     private String isbn;
     private String authorId;

    public BooksauthorsId() {
    }

    public BooksauthorsId(String isbn, String authorId) {
       this.isbn = isbn;
       this.authorId = authorId;
    }
   
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BooksauthorsId) ) return false;
		 BooksauthorsId castOther = ( BooksauthorsId ) other; 
         
		 return ( (this.getIsbn()==castOther.getIsbn()) || ( this.getIsbn()!=null && castOther.getIsbn()!=null && this.getIsbn().equals(castOther.getIsbn()) ) )
 && ( (this.getAuthorId()==castOther.getAuthorId()) || ( this.getAuthorId()!=null && castOther.getAuthorId()!=null && this.getAuthorId().equals(castOther.getAuthorId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIsbn() == null ? 0 : this.getIsbn().hashCode() );
         result = 37 * result + ( getAuthorId() == null ? 0 : this.getAuthorId().hashCode() );
         return result;
   }   


}


