package bookshop;
// Generated Oct 29, 2016 7:28:58 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {


     private String isbn;
     private String title;
     private String publisherId;
     private String categoryId;
     private BigDecimal price;
     private Set<Booksauthors> booksauthorses = new HashSet<Booksauthors>(0);

    public Books() {
    }

	
    public Books(String isbn) {
        this.isbn = isbn;
    }
    public Books(String isbn, String title, String publisherId, String categoryId, BigDecimal price, Set<Booksauthors> booksauthorses) {
       this.isbn = isbn;
       this.title = title;
       this.publisherId = publisherId;
       this.categoryId = categoryId;
       this.price = price;
       this.booksauthorses = booksauthorses;
    }
   
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublisherId() {
        return this.publisherId;
    }
    
    public void setPublisherId(String publisherId) {
        this.publisherId = publisherId;
    }
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public Set<Booksauthors> getBooksauthorses() {
        return this.booksauthorses;
    }
    
    public void setBooksauthorses(Set<Booksauthors> booksauthorses) {
        this.booksauthorses = booksauthorses;
    }




}


