package bookshop;
// Generated Oct 29, 2016 7:28:58 PM by Hibernate Tools 4.3.1



/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private String categoryId;
     private String categoryName;

    public Categories() {
    }

	
    public Categories(String categoryId) {
        this.categoryId = categoryId;
    }
    public Categories(String categoryId, String categoryName) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
    }
   
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }




}


